# Generated by Django 5.0.1 on 2024-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_status',
            field=models.BooleanField(default=False),
        ),
    ]
